---

- name: Include variables for Debian.
  include_vars: Debian.yml
  when: ansible_os_family == 'Debian'
- name: Include variables for RedHat
  include_vars: RedHat.yml
  when: ansible_os_family == "RedHat"
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8

- import_tasks: native.yml
  when: viewfinderjs_setup == 'native'

- import_tasks: docker.yml
  when: viewfinderjs_setup == 'docker'
