---
# handlers file for juju4.viewfinderjs

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker")
        )

- name: restart viewfinderjs
  service:
    name: viewfinderjs
    state: restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker")
        )

- name: restart rsyslog
  service: name=rsyslog state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker") and
          (ansible_distribution == 'Alpine' or ansible_os_family == 'RedHat')
        )
