---

- name: Verify native install
  hosts: browserhosts
  gather_facts: true
  pre_tasks:
    - name: Debian vars
      set_fact:
        chromium_pkg: chromium-browser
      when: ansible_os_family == 'Debian'
    - name: RedHat vars
      set_fact:
        chromium_pkg: chromium
      when: ansible_os_family == "RedHat"
  tasks:
    - name: Debug | ansible_virtualization_type
      debug: var=ansible_virtualization_type verbosity=1

    - name: Gather package facts
      package_facts:
        manager: auto
    - name: Validate that needed packages are present
      assert:
        that: ansible_facts.packages['git'] and ansible_facts.packages['pulseaudio'] and ansible_facts.packages[chromium_pkg]

    - name: Ensure docViewer.js file is present
      stat:
        path: /var/_viewfinderjs/viewfinderjs/secrets/docViewer.js
      register: dv
    - name: Validate docViewer.js present
      assert:
        that: dv.stat.exists and dv.stat.size != 0

    - name: Ensure process is running
      command: pgrep -u _viewfinderjs node
      register: ps
      changed_when: false
      failed_when: false
    - name: Validate ps output
      assert:
        that: ps.stdout
      when: >
        not (ansible_virtualization_type is defined and
              (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
            )

    - name: Ensure ports are listening
      wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items:
        - { h: localhost, p: 8002 }
      # FIXME!
      failed_when: false
      when: >
        not (ansible_virtualization_type is defined and
              (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
            )

    - name: List npm package
      command: npm list
      args:
        chdir: /var/_viewfinderjs/viewfinderjs
      register: npml
      changed_when: false
      # FIXME!
      failed_when: false
      become: yes
      become_user: _viewfinderjs

    - name: Debug | npm list output
      debug: var=npml

    - name: List npm outdated package
      command: npm outdated
      args:
        chdir: /var/_viewfinderjs/viewfinderjs
      register: npmo
      changed_when: false
      # FIXME!
      failed_when: false
      become: yes
      become_user: _viewfinderjs
    - name: Debug | npm outdated output
      debug: var=npmo

    - name: npm audit
      command: npm audit
      args:
        chdir: /var/_viewfinderjs/viewfinderjs
      register: npma
      changed_when: false
      # FIXME!
      failed_when: false
      become: yes
      become_user: _viewfinderjs
    - name: Debug | npm audit output
      debug: var=npma
    - name: Validate no vulnerabilities found by npm audit
      assert:
        that: >
          "'found 0 vulnerabilities' not in npma.stdout"

# /var/_viewfinderjs/chrome-browser/chrome-err.log
# error, permission denied
